### ISSUE TITLE
Asynchronous / non-blocking version

### ISSUE THREAD

**Issue by orzechow** [johannes-graeter/lightclock#2]
Right now, the alarm class only provides a blocking `spin()` function, that never returns:

https://github.com/johannes-graeter/lightclock/blob/5361651ce414a5ba01e7bfea075965784fa00609/main.py#L90

In order to provide the Webapp (see #1), I propose to write the spinning loop in the `main.py` and spin each "process" once. This would enable the clock to wait for the alarm time or adjust the light while the webapp is available to the end user.

This means `Alarm.spin_once()` would be without 
https://github.com/johannes-graeter/lightclock/blob/5361651ce414a5ba01e7bfea075965784fa00609/alarm.py#L97
and even 
https://github.com/johannes-graeter/lightclock/blob/5361651ce414a5ba01e7bfea075965784fa00609/clock_actions_micropython.py#L54
should be written in a non-blocking fashion.

**Comment by johannes-graeter** [comment]
pushed non blocking version into branch asynchron.
spin_once calls process_once which adjusts light accroding to current time diff... illumination could jump if the program is lacky though, must be tested on feather...

**Comment by johannes-graeter** [comment]
@orzechow ist that what you were suggesting?
