### ISSUE TITLE
Provide config struct and loader class

### ISSUE THREAD

**Issue by orzechow** [johannes-graeter/lightclock#3]
Right now the config is loaded in `main.py` and written to global variables, that are then passed as arguments to the other classes.

I suggest cleaning up this interface, by providing a class that loads the config from the yaml file(s) as a struct.

This would enable us to pass that config struct to whoever needs specific settings, especially when they have changed during operation (via Webapp #1).

**Comment by johannes-graeter** [comment]
TimeSetter, Alarm and ClockActions... have now set_config() functions in which a config file can be passed and all parameters that make sense to the class are set

**Comment by johannes-graeter** [comment]
didn't want to read the config in each class, I think it is cleaner if it is read in main and passed to each of the classes

**Comment by johannes-graeter** [comment]
it is on branch asynchronous.

**Comment by johannes-graeter** [comment]
what do you think about it?

**Comment by orzechow** [comment]
That looks well! One thing though: `set_config()` is now redundantly in four files/classes. I worry about memory usage (I'm really short on free mem with the webapp itself...)  
How about a superclass like `WithConfig` that defines `set_config()`? Then TimeSetter, Alarm and ClockActions can inherit from it and only need to define their own `func_mapping`

**Comment by johannes-graeter** [comment]
done and pushed in asynchron
